version: '3.8'

services:
  db:
    container_name: postgres-resume-dev
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:  
    image: dpage/pgadmin4  
    container_name: pgadmin4_container  
    restart: always  
    ports:  
      - "8888:80"  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:  
      - pgadmin-data:/var/lib/pgadmin  
  
volumes:  
  postgres-data:
  pgadmin-data: